version: '3.1'
services:
  mongo:
    image: mongo:latest
    networks:
    - forum-media-net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ForumMediaData
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    networks:
      - forum-media-net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - forum-media-net
    ports:
      - 5000:80
    environment:
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  forum-media-net: