version: '3.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: 9GagMedia
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Noobmaster69
        
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Noobmaster69
      ME_CONFIG_MONGODB_SERVER: mongo
  
  flask-webserver:
    image: myflaskapp:latest
    ports:
      - 5000:80
    volumes:
      - ./drivers:/usr/local/bin/drivers
    environment:
      MONGO_INITDB_HOST: mongo
      WEB_CONCURRENCY: 1
      WEBDRIVER_EXECUTABLE_PATH: /usr/local/bin/drivers/geckodriver-linux
